---

language: python
python: "2.7"
sudo: required
dist: trusty

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nvalidate_certs=False\nroles_path=../' > ansible.cfg

  # Check ansible version
  - ansible --version

script:
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local

  - ansible-playbook tests/test.yml -i tests/inventory --connection=local

  - /usr/bin/node --version

  - /usr/bin/npm --version

  - /usr/bin/yarn --version

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
