---

- name: add yarn apt-key
  apt_key:
    id: 86E50310
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present
  become: yes

- name: add yarn repository
  apt_repository:
    repo: "deb https://dl.yarnpkg.com/debian/ stable main"
    state: present
  become: yes

- name: install yarn
  apt:
    name: yarn
    state: latest
  become: yes
